---
title: "how-to-use"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how-to-use}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(RepliSeq)
```

# readRS(paths_data,fractions) :

This functions reads Repli-seq assays from multiple files (one file for one fraction) and outputs a dataframe from it.
It requires bedgraph inputs with a one line header listing options, with **no other comments** such as : [(bedgraph spec)](http://genome.ucsc.edu/goldenPath/help/bedgraph.html)   
track 	type=bedGraph 	name=NT_chr22-s1	description=50kbprofile   
chr22	0	50000	0   
chr22	50000	100000	0   

```{r}

### args :
temp.paths <- c("../inst/extdata/NT_chr22-s1.bdg","../inst/extdata/NT_chr22-s2.bdg","../inst/extdata/NT_chr22-s3.bdg",
                "../inst/extdata/NT_chr22-s4.bdg","../inst/extdata/NT_chr22-s5.bdg","../inst/extdata/NT_chr22-s6.bdg")
temp.fractions <- c("S1","S2","S3","S4","S5","S6")


### 2 fractions RepliSeq
# apply function :
RS_early <- readRS(temp.paths[1:2],temp.fractions[1:2])
# outputs :
head(RS_early)
print(typeof(RS_early))
print(summary(RS_early))

### 6 fractions RepliSeq
# apply function :
RS_all <- readRS(temp.paths,temp.fractions)
# outputs :
head(RS_all)
typeof(RS_all)
summary(RS_all)

```

# calculateS50(rs_assay,fractions) :

```{r}

### 2 fractions RepliSeq
# apply function :
temp.S50 <- RepliSeq::calculateS50(RS_early,temp.fractions[1:2])
# outputs :
tail(temp.S50)
summary(temp.S50$S50)

### 6 fractions RepliSeq
# apply function :
temp.S50 <- RepliSeq::calculateS50(RS_all,temp.fractions)
# outputs :
tail(temp.S50)
summary(temp.S50$S50)

```

